### ISSUE TITLE
Week from Monday

### ISSUE THREAD

**Issue by TonyRotay** [sassy-labs/datepicker#10]
Hi! Can someone help me, what should I edit in package files to make weeks starting from monday?

**Comment by siddharthborderwala** [comment]
Will add a configuration option for the same.

**Comment by jomarmen** [comment]
I'm interesting too

**Comment by siddharthborderwala** [comment]
I'll start work on this and will release it in the next version.

Sorry for the delay and thanks a lot for using my library!

**Comment by siddharthborderwala** [comment]
I have added configuration options and added an inbuilt year-picker and month-picker too.

The changes can be found in PR #11 - `v0.9.0`

Planning to release the new version in a couple of days

**Comment by siddharthborderwala** [comment]
@jomarmen @TonyRotay Update your package to 0.9.0 and you will have access to configure the first day of week.

Here is a snippet -
```jsx
function Example() {
  const [date, setDate] = useState(new Date());

  const onChange = newDate => {
    console.log(`New date selected - ${newDate.toString()}`);
    setDate(newDate);
  };

  // in this datepicker the week will start from Monday
  return <DatePicker onChange={onChange} value={date} options={{ weekStartsFrom: 'Monday' }} />;
}
```
