### ISSUE TITLE
This Library is too beautiful, can we get a React Native Implementation

### ISSUE THREAD

**Issue by zaghadon** [sassy-labs/datepicker#13]
Hi Guys, this library is the perfect definition of what a Library should be, beautiful, working, with little dependencies, zero open issues, and actively maintained.

There seems to be no React Native Component for Date Handling with these qualities and a beautiful Interface. Can we get a React Native Implementation of Sassy???

**Comment by siddharthborderwala** [comment]
Hello @zaghadon 👋🏻

I am glad you checked out my library and thank you for your words of appreciation. I am not sure how to port this library to react-native, and it is not in my plans for the near future.

Right now I am working on a few optimisations and correcting behaviour and styling of some elements. Once that is done, I am planning to create proper documentation site for the same and add arrow key support for the datepicker.

I am hoping to release v1.0.0 with the above mentioned work done by November end. Once I reach the v1.0.0 milestone, if there are more requests to support react native, I will surely work on extending support.
