### ISSUE TITLE
TimePicker value cannot be set

### ISSUE THREAD

**Issue by michaelwhite404** [sassy-labs/datepicker#16]
When I set the value of the time picker, the prop doesn't change the actual value of the time. It seems as if the internal state isn't set correctly. I took a look at the component and I think the problem is the first 'alignTime' function isn't being returned, meaning the initial value will always be the value of the current time from the second 'alignTime' function.

https://github.com/sassy-labs/datepicker/blob/769b90b3f61fa31a41d20463a7181a7fec0b0ad3/src/time-picker/index.tsx#L84-L91

<img width="1268" alt="Screen Shot 2022-11-18 at 7 34 57 PM" src="https://user-images.githubusercontent.com/54529939/202825160-9867ab9d-d5f9-402f-a535-fb44d6a9e3b7.png">

**Comment by siddharthborderwala** [comment]
Hey @michaelwhite404 thanks a lot for pointing this out! It is a bug, and a severe one - I don't know how it has been missed so far. I will push out a fix As soon as possible!

**Comment by siddharthborderwala** [comment]
Fixed in version 0.10.2
