### ISSUE TITLE
Missing "./dist/styles.css" export in "sassy-datepicker" package

### ISSUE THREAD

**Issue by DocSJ1980** [sassy-labs/datepicker#17]
I am getting the following error

Internal server error: Missing "./dist/styles.css" export in "sassy-datepicker" package

I am using sassy-datepicker in react and am able to get the following output. However the output is not properly formatted and what i can think is that it is due to non applying of css styles. I have checked styles.css file is present in dist folder of the package and after giving its import path in my component file or main.js file i get the above error.

Thanks for helping.

![image](https://user-images.githubusercontent.com/106554079/209298986-01584536-c027-455a-a28a-17fa80618382.png)

**Comment by ghost** [comment]
Hi @DocSJ1980 you will need to do the following

```jsx
import 'sassy-datepicker/dist/styles.css'
```

Make sure you are using an appropriate development setup including a bundler and a css loader.
