### ISSUE TITLE
Changing the Week Starts From the property from "Sunday" to "Monday" doesn't work

### ISSUE THREAD

**Issue by PrzemekGalarowicz** [sassy-labs/datepicker#18]
Hi,

I figured out that Changing the Week Starts From the property from "Sunday" to "Monday" doesn't work. It changes only the day names order, but the day's view doesn't rerender. I attached screenshots.

![Screenshot (261)](https://user-images.githubusercontent.com/7968018/230630572-d0518657-b750-4804-b9e2-5cf85cb5f2ff.png)
![Screenshot (260)](https://user-images.githubusercontent.com/7968018/230630577-7f0a8618-e7b3-47d9-99b8-5faa3caebbf5.png)

**Comment by siddharthborderwala** [comment]
Hi Przemysław! I’m glad you’re using the library that I created 😃

Thanks for raising an issue on GitHub and reaching out to me about the same.

I checked the documentation site and I tried out the “week starts from” option and it appears to work for me.

Here’s the screenshots -

![IMG_2636](https://user-images.githubusercontent.com/54456279/235140330-739547b4-7a0f-4509-ad8f-b6b5b37479e4.jpeg)
![IMG_2635](https://user-images.githubusercontent.com/54456279/235140357-142d6677-da86-4184-9b1d-619e373e7880.jpeg)
