### ISSUE TITLE
The arrow in the calender is not visible in IOS

### ISSUE THREAD

**Issue by Chandanesh32** [sassy-labs/datepicker#4]
Currently am using the Sassy -date picker and it works fine on android phones,
but in the IOS devices, I cannot able to see the arrow key as attached in the below screenshot.

 
![WhatsApp Image 2022-01-08 at 1 30 12 PM](https://user-images.githubusercontent.com/74053358/148636903-e01ac47f-3c46-448c-af4c-c3ef6db04bd6.jpeg)

would be helpful if anyone encountered this or any suggestions will help me to fix this?

Thanks in advance
Chandanesh

**Comment by siddharthborderwala** [comment]
The library is working without any problems in other iOS devices. It would help if you have a macbook and could connect your iOS device to it and inspect what is going on. There isn't a way for me to help here before I could get some more information about this, as I don't have a MacOS device to take a look at what exactly is going on here.
